### ISSUE TITLE
Could you please list the version requirements for each dependency used in the tutorial?

### ISSUE THREAD

**Issue by PhrenoVermouth** [xing-lab-pitt/GraphVelo#1]
As title (anndata .... cellrank). Thanks!

**Comment by yhchen1123** [comment]
Hi Gran,

Thanks for your interest in our work!

I have updated the tutorial for the convinience of understanding and reproducing our results. And I listed package versions that might influence the numerical and plotting results with the help of cellrank2 buildin function. 

Please let me know if you have any further questions. 

Best regards,
Yuhao

**Comment by PhrenoVermouth** [comment]
Thanks for your swift feedback, Yuhao! Merry Xmas!
